### ISSUE TITLE
이거 저만 이럼?

### ISSUE THREAD

**Issue by ParkChanSol** [PIEA/Essentials#1]
![image](https://cloud.githubusercontent.com/assets/20399222/25844821/b01fddc6-34e6-11e7-94cf-c8f4cd4e68e7.png)
으아아아아ㅏ아아ㅏ

**Comment by BluePickaxe** [comment]
먼저 Essentials 폴더 생성되는지 확인좀요..

**Comment by ParkChanSol** [comment]
@BluePickaxe 
![image](https://cloud.githubusercontent.com/assets/20399222/25899675/b3d7ce2a-35cb-11e7-942b-1dc40babd8ac.png)
생성은 잘되요
